# Source: cd-indicators/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cd-indicators
  labels:
    app.kubernetes.io/name: cd-indicators
    app.kubernetes.io/instance: "cd-indicators"
    helm.sh/chart: cd-indicators-0.0.10
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: "Helm"
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups:
      - jenkins.io
    resources:
      - pipelineactivities
      - releases
    verbs:
      - list
      - watch
      - get
