# Source: loki/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: loki
  namespace: jx-observability
  labels:
    app: loki
    chart: loki-2.5.0
    release: loki
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: local
  data:
    - name: loki.yaml
      key: loki.yaml
      property: loki.yaml
  template:
    metadata:
      labels:
        app: loki
        chart: loki-2.5.0
        release: loki
        heritage: Helm
