{
 "title": "cert-manager",
 "tags": [
  "jenkins-x",
  "cert-manager"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Certificates expiration dates",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (name) (certmanager_certificate_expiration_timestamp_seconds*1000)"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{container=\"cert-manager\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{container=\"cert-manager\"})"
    }
   ]
  },
  {
   "title": "Certificates statuses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(certmanager_certificate_ready_status{condition=\"True\"} == 1)",
     "legendFormat": "ready"
    },
    {
     "expr": "count(certmanager_certificate_ready_status{condition=\"False\"} == 1)",
     "legendFormat": "not ready"
    },
    {
     "expr": "count(certmanager_certificate_ready_status{condition=\"Unknown\"} == 1)",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({app=\"cert-manager\"} |~ \"(?i)$search\" [$__interval])",
     "legendFormat": "logs"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{app=\"cert-manager\"} |~ \"(?i)$search\" | json | line_format \"{{.log}}\""
    }
   ]
  }
 ]
}