# Source: osiris/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osiris
  labels:
    app.kubernetes.io/name: osiris
    helm.sh/chart: osiris-0.0.48
    app.kubernetes.io/instance: osiris
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
      - create
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - update
      - patch
